### ISSUE TITLE
Broken EMIT in 5.05.00 (2019.05.10) release

### ISSUE THREAD

**Issue by JohnMSmith** [MethodicalAcceleratorDesign/MAD-X#778]
After the release of 5.05.00 longitudinal emittance in EMIT is getting calculated wrong. SIGE and SIGT therefore are wrong too. 

Here are the examples of EMIT results before and after the release. 

BEFORE
```
enter EMIT module

 Global parameters for electrons, radiate = T:

 C               476.141035760093 m          f0             0.629629523891876 MHz
 T0              1.58823556084026 musecs     alfa        0.000123943456713351
 eta         0.000123914443388583            gamma(tr)       89.8231327644455
 Bcurrent                       0 A/bunch    Kbunch             1
 Npart                          0 /bunch     Energy                         3 GeV
 gamma           5870.85359548455            beta           0.999999985493337
 dtbyds                         0
     U0              0.418965 [MeV/turn]

                                                  M o d e   1         M o d e   2         M o d e   3
 Fractional tunes            undamped              0.78125928          0.82513233          0.00147969
                             damped                0.78125928          0.82513233          0.00147964

 beta* [m]                   x                 0.11908922E+02      0.59912972E-41      0.18392578E-10
                             y                 0.21313932E-38      0.17697611E+01      0.75594957E-31
                             t                 0.91226161E-11      0.26085065E-30      0.63462187E+01

 gamma* [1/m]                px                0.83970658E-01      0.14700591E-41      0.91690700E-12
                             py                0.19131969E-40      0.56504803E+00      0.35526770E-31
                             pt                0.66756058E-12      0.10691844E-30      0.15757415E+00

 beta(max) [m]               x                 0.15456466E+02      0.71153277E-40      0.53637278E-03
                             y                 0.90134217E-34      0.18574484E+02      0.75955983E-31
                             t                 0.39535683E-03      0.62180555E-29      0.63462189E+01

 gamma(max) [1/m]            px                0.28435130E+02      0.10944617E-39      0.91690700E-12
                             py                0.62584456E-34      0.28489716E+02      0.35526770E-31
                             pt                0.27497641E-03      0.95299986E-29      0.15757418E+00

 Damping partition numbers                         1.95554060          1.00000038          1.04446067
 Damping constants [1/s]                           0.85976177E+02      0.43965443E+02      0.45920159E+02
 Damping times [s]                                 0.11631129E-01      0.22745136E-01      0.21776928E-01
 Emittances [pi micro m]                       0.89798404E-04      0.59682303E-31      0.47866605E+01

 EMIT: beam parameters have been updated.
beam->ex           =  8.97984043596838e-011 ;
beam->sige         =   0.000868477959789949 ;
beam->sigt         =    0.00551155103011372 ;

++++++ table: summ

            length             orbit5               alfa            gammatr
       476.1410358   1.636729477e-017    0.0001239434567        89.82313276

                q1                dq1            betxmax              dxmax
       53.78129224   -0.0001287077112         15.4560076      0.05009055796

             dxrms             xcomax             xcorms                 q2
      0.0386214414   1.457586736e-021     6.4030627e-022        16.82513079

               dq2            betymax              dymax              dyrms
      0.0384519403        18.57414104                  0                  0

            ycomax             ycorms             deltap            synch_1
                 0                  0                  0      0.06033826657

           synch_2            synch_3            synch_4            synch_5
      0.3673771522      0.02191293742      -0.3481022502   4.926127661e-006
```

AFTER
> 
```
enter EMIT module

 Global parameters for electrons, radiate = T:

 C               476.141035760093 m          f0             0.629629523891876 MHz
 T0              1.58823556084026 musecs     alfa         0.00012394563390588
 eta         0.000123916620581112            gamma(tr)        89.822343857623
 Bcurrent                       0 A/bunch    Kbunch             1
 Npart                          0 /bunch     Energy                         3 GeV
 gamma           5870.85359548455            beta           0.999999985493337
 dtbyds                         0
     U0              0.418965 [MeV/turn]

                                                  M o d e   1         M o d e   2         M o d e   3
 Fractional tunes            undamped              0.78129504          0.82513542          0.00147970
                             damped                0.78129504          0.82513542          0.00147970

 beta* [m]                   x                 0.11909090E+02      0.60099963E-42      0.29927757E-11
                             y                 0.55871903E-40      0.17696786E+01      0.43791786E-31
                             t                 0.30696294E-11      0.16748161E-30      0.63462986E+01

 gamma* [1/m]                px                0.83969540E-01      0.14716196E-42      0.39917973E-17
                             py                0.79752623E-43      0.56507436E+00      0.29102317E-31
                             pt                0.17990444E-13      0.14743273E-30      0.15757557E+00

 beta(max) [m]               x                 0.15519285E+02      0.71392236E-41      0.53848435E-03
                             y                 0.73213196E-34      0.18583390E+02      0.47980247E-31
                             t                 0.39628298E-03      0.65709755E-29      0.63462986E+01

 gamma(max) [1/m]            px                0.28606274E+02      0.10980496E-40      0.39917973E-17
                             py                0.50927168E-34      0.28502560E+02      0.29102317E-31
                             pt                0.27561313E-03      0.10022790E-28      0.15757557E+00

 Damping partition numbers                         1.95596358          0.99999952          0.04403543
 Damping constants [1/s]                           0.85994820E+02      0.43965429E+02      0.19360374E+01
 Damping times [s]                                 0.11628607E-01      0.22745143E-01      0.51651894E+00
 Emittances [pi micro m]                       0.89759264E-04      0.36165693E-31      0.11353277E+03

 EMIT: beam parameters have been updated.

++++++ table: summ

                length                 orbit5                   alfa                gammatr
      476.141035760101    -0.0828063836809238   0.000123946007128949       89.8222086221409

                    q1                    dq1                betxmax                  dxmax
      53.7812950433151  -0.000336797256750287       15.5192849973803     0.0501485369025589

                 dxrms                 xcomax                 xcorms                     q2
    0.0375454852925604  3.52431846501714e-006  1.51367960652074e-006       16.8251354184065

                   dq2                betymax                  dymax                  dyrms
    0.0385671086178263       18.5833895051507                      0                      0

                ycomax                 ycorms                 deltap                synch_1
                     0                      0                      0     0.0600427848756328

               synch_2                synch_3                synch_4                synch_5
     0.367377152172693     0.0219129374172355     -0.347936416243369  4.91565282262378e-006

                nflips
                     0

beam->ex           =  8.97592638251677e-011 ;
beam->sige         =    0.00422965611937638 ;
beam->sigt         =     0.0268423705639318 ;
```

**Comment by tpersson** [comment]
Thanks for reporting. Since, the problem is related already to the difference in longitudinal emittance the difference must be related to the changes implemented by Andrea. He also fixed issues in some of the equations so maybe the difference is from there. 
Could you provide the script, or a simplified  version where we see this difference, so we can check where it might come from? 
@alatina what do you think?

**Comment by JohnMSmith** [comment]
Here is the script. 
[script.zip](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/3190565/script.zip)

**Comment by alatina** [comment]
Hello Tobias,
I am looking into this. Will report about my findings ASAP.
Andrea

**Comment by alatina** [comment]
This is my report after a detailed study of the case:

The old version of MAD-X had imported the module EMIT from the old MAD8 files and, with it, a number of incorrect assumptions:

(i) the momentum lost via synchrotron radiation was assimilated to the energy lost, i.e.: P_lost = E_lost, which is not an exact assumption;

(ii) the phase space's sixth variable, p_t, was equalled to the momentum difference, d = (P-P0) / P0, which again is not a correct assumption, as in fact p_t = (E-E0) / (P0*c), i.e. the canonical variable partner of the fifth coordinate: the arrival time difference;

(iii) the momentum's "shirking factor" due to radiation, experienced by a particle, was computed relatively to the reference momentum, P0, rather than to the initial's momentum of the particle itself.

In the last version of MAD-X all these assumptions have been eliminated, and a rewriting of a new derivation of the equations was carried out without such approximations.

Therefore I believe that the results of the new version are correct, whereas the result of the old version were not correct.

**Comment by JohnMSmith** [comment]
The summ of damping partition numbers must be 4, you have 3. Therefore I believe that the results of the new versioan are incorrect.

**Comment by alatina** [comment]
OK. I am investigating the issue.

**Comment by alatina** [comment]
@JohnMSmith I just pushed to my branch, al-dev, a potential fix. Could you please test it and tell me if it gives the expected results?

**Comment by JohnMSmith** [comment]
I have tested your fix. It appears to be giving expected results.

```
++++++ table: summ

            length             orbit5               alfa            gammatr 
       476.1410358     -0.08280623796    0.0001239448634        89.82262303 

                q1                dq1            betxmax              dxmax 
       53.78122177    -0.001182179687        15.49557669      0.05034297609 

             dxrms             xcomax             xcorms                 q2 
     0.03759814713    8.641904322e-06    3.404480767e-06        16.82513565 

               dq2            betymax              dymax              dyrms 
     0.03947562277        18.61973049                  0                  0 

            ycomax             ycorms             deltap            synch_1 
                 0                  0                  0      0.06004257694 

           synch_2            synch_3            synch_4            synch_5 
      0.3673771522      0.02191293742      -0.3479387341    4.915866754e-06 

            nflips 
                 0 
enter EMIT module
 
 Global parameters for electrons, radiate = T:

 C                476.1410358 m          f0              0.6296295239 MHz
 T0               1.588235561 musecs     alfa         0.0001239452516 
 eta          0.0001239162383            gamma(tr)        89.82248237 
 Bcurrent                   0 A/bunch    Kbunch             1 
 Npart                      0 /bunch     Energy                     3 GeV 
 gamma            5870.853595            beta            0.9999999855
 dtbyds                     0
     U0              0.418965 [MeV/turn]
 
                                                  M o d e   1         M o d e   2         M o d e   3
 Fractional tunes            undamped              0.78122171          0.82513565          0.00147969
                             damped                0.78122171          0.82513565          0.00147965
 
 beta* [m]                   x                 0.11887004E+02      0.98962677E-42      0.27874293E-08
                             y                 0.66096772E-38      0.17657051E+01      0.18710594E-31
                             t                 0.11777708E-07      0.42721185E-31      0.63462612E+01
 
 gamma* [1/m]                px                0.84125494E-01      0.12323821E-41      0.34072828E-09
                             py                0.37273496E-39      0.56634599E+00      0.74075127E-31
                             pt                0.13522313E-09      0.40076706E-31      0.15757610E+00
 
 beta(max) [m]               x                 0.15495577E+02      0.50348063E-40      0.53894259E-03
                             y                 0.19254763E-33      0.18619730E+02      0.18710598E-31
                             t                 0.39936921E-03      0.17587731E-29      0.63462811E+01
 
 gamma(max) [1/m]            px                0.28557912E+02      0.77524431E-40      0.34072828E-09
                             py                0.13262169E-33      0.28560491E+02      0.74116308E-31
                             pt                0.27663439E-03      0.27044141E-29      0.15757610E+00
 
 Damping partition numbers                         1.95597481          1.00000133          1.04402693
 Damping constants [1/s]                           0.85995270E+02      0.43965486E+02      0.45901091E+02
 Damping times [s]                                 0.11628547E-01      0.22745114E-01      0.21785975E-01
 Emittances [pi micro m]                       0.89762867E-04      0.13944045E-31      0.47886280E+01

 EMIT: beam parameters have been updated.

 RF system: 
 Cavity                      length[m]        voltage[MV]                lag          freq[MHz]             harmon
 rf                                  0             0.7215                0.5          356.99994                567
beam->ex           =    8.976286735e-11 ;
beam->sige         =    0.0008686618084 ;
beam->sigt         =     0.005512702098 ;
```

**Comment by alatina** [comment]
@JohnMSmith Thank you for the fast feedback. You can use this new version, for now. I am still looking into the details of the code, to understand better what the problem was.

**Comment by bogomyag** [comment]
Hello,
you have a problem with the sum of partition numbers not equal to 4 for two months already.
Could you fix it asap, please? Or return the old emit.
Thank you,
Anton

**Comment by alatina** [comment]
@bogomyag : The problem has been fixed. Please use the latest version.

**Comment by bogomyag** [comment]
[Test.zip](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/3405834/Test.zip)
The problem is not fixed.
 ++++++++++++++++++++++++++++++++++++++++++++
  +     MAD-X 5.05.01  (64 bit, Windows)     +
  + Support: mad@cern.ch, http://cern.ch/mad +
  + Release   date: 2019.06.07               +
  + Execution date: 2019.07.18 16:27:53      +
  ++++++++++++++++++++++++++++++++++++++++++++

Damping partition numbers                         0.99654153          1.00000003          1.00345850

**Comment by bogomyag** [comment]
I am not able to find .exe file for windows on github. If you want users to compile it than provide a list of necessary libraries and how to compile it on windows.

This is a major error having wrong partition numbers. Please, provide the .exe file.

Thank you,
Anton

**Comment by alatina** [comment]
The latest version of MAD-X (on GitHub, and I mean the source code) works correctly on your test.
As I said, the problem has been fixed.

We are about to release a new release, which will provide you with the Windows .exe file.
I am checking with my colleagues when the new release will be made.

Meanwhile, compiling the current GitHub source code will give you the expected partition numbers.

**Comment by tpersson** [comment]
Dear Anton,

The executables are not available on GitHub. We were planning to make a new release next weekend but in case you need it more urgently I could provide one for you tomorrow ( not at work today ). Would that work ?

Best regards
Tobias



-------- Original message --------

**Comment by bogomyag** [comment]
Thank you alatina and Tobias,

I can and will wait for the next weekend. I have been using MAD-X 5.04.02 since the mistake was observed.

Concerning the latest version of MAD-X on github, I could not find instructions on how to compile MAD-X on windows. 

Also, the message to @JohnMSmith was "I just pushed to my branch, al-dev, a potential fix. Could you please test it and tell me if it gives the expected results?" 
The branch does not exist anymore and it is not clear if the latest version had the fix.

Respectfully,
Anton

**Comment by alatina** [comment]
You are welcome.

Once verified that the implementation in 'al-dev' was giving the expected partition numbers, the branch was reintegrated and then deleted.
